import type { Metadata } from "next";
import "./globals.css";
import SideNav from "@/components/SideNav/SideNav";

export const metadata: Metadata = {
  title: "GoGo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <div className="fixed left-0 top-0 flex h-screen w-1/5 flex-col items-center justify-between bg-dark-green p-6 py-4">
          <h1 className="text-4xl">GoGo</h1>
          <SideNav />
        </div>
        <main className="ml-[20%] flex-grow p-4">{children}</main>
      </body>
    </html>
  );
}
