import type { Metadata } from "next";
import "./globals.css";
import SideNav from "@/components/SideNav/SideNav";

export const metadata: Metadata = {
  title: "GoGo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <SideNav />

        <main className="ml-[20%] flex-grow p-4">{children}</main>
      </body>
    </html>
  );
}
